name: Python CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'
    
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Install dependencies
        run: |
          uv pip install -e .
          uv pip install pytest pytest-cov pytest-mock flask
      
      - name: Run tests
        run: |
          uv run pytest -s